# K-Means clustering using scikit-learn

In this notebook we apply scikit-learn’s K-Means implementation to the normalized zone-hour feature matrix in order to segment demand patterns into behavioral clusters. The resulting cluster labels are used in the following tasks for evaluation, visualization and business interpretation.

In [2]:
import numpy as np
import pandas as pd

from sklearn.cluster import KMeans

DATA_PATH = "../../data/processed/clustering_features_scaled.parquet"

In [3]:
X_scaled_df = pd.read_parquet(DATA_PATH)
X_scaled_df.shape

(296807, 6)

In [4]:
X = X_scaled_df.values

In [5]:
X

array([[-0.51060548,  2.80433372,  2.57368633, -0.2688393 , -1.03270344,
        -0.63153158],
       [-0.51771742,  7.69128887,  3.09159913,  0.03688014, -1.03270344,
        -0.63153158],
       [-0.51771742,  5.76963871,  7.83481719,  0.49545931, -1.03270344,
        -0.63153158],
       ...,
       [-0.51771742,  1.18285857,  2.09677496,  1.41261765,  1.5004962 ,
         1.58345209],
       [-0.51060548,  0.02026022,  0.3240026 ,  1.56547738,  1.5004962 ,
         1.58345209],
       [-0.51771742, -0.62481786, -0.60068754,  1.7183371 ,  1.5004962 ,
         1.58345209]], shape=(296807, 6))

### Fit K-means
We start with a fixed number of clusters and evaluate the results in later steps.

In [6]:
k = 4
kmeans = KMeans(
    n_clusters=k,
    random_state=42,
    n_init=10
)

kmeans.fit(X)

KMeans(n_clusters=4, n_init=10, random_state=42)

Extract cluster assignments and centroid coordinates.

In [7]:
labels = kmeans.labels_
centroids = kmeans.cluster_centers_

In [8]:
labels.shape

(296807,)

In [9]:
centroids.shape

(4, 6)

In [10]:
centroids

array([[ 2.38819189, -0.49701459, -0.55443855,  0.5512178 , -0.25125029,
        -0.38943952],
       [-0.29867274, -0.29207285, -0.30158807, -0.08789578, -0.5188236 ,
        -0.63153158],
       [-0.12707455, -0.27911753, -0.2717378 , -0.05733254,  1.25341023,
         1.58345209],
       [-0.41368863,  1.93672901,  2.00019919,  0.02453241, -0.16809482,
        -0.24768131]])

In [11]:
# Attach cluster labels to the normalized feature table
df_clusters = X_scaled_df.copy()
df_clusters["cluster"] = labels

df_clusters.head()

demand  avg_fare  avg_distance      hour  day_of_week  is_weekend  \
0 -0.510605  2.804334      2.573686 -0.268839    -1.032703   -0.631532   
1 -0.517717  7.691289      3.091599  0.036880    -1.032703   -0.631532   
2 -0.517717  5.769639      7.834817  0.495459    -1.032703   -0.631532   
3 -0.517717  0.733590     -0.799221 -1.491717    -0.526064   -0.631532   
4 -0.517717 -0.260367      1.656549 -1.338857    -0.526064   -0.631532   

   cluster  
0        3  
1        3  
2        3  
3        1  
4        1

Check the size of each cluster to ensure no empty or degenerate clusters exist.

In [12]:
np.bincount(labels)

array([ 30027, 151352,  74219,  41209])

In [13]:
AGG_PATH = "../../data/processed/nyc_demand_zone_hour_2019_q1.parquet"

# Load clean snapshot
df = pd.read_parquet(AGG_PATH)

In [14]:
df["cluster"] = labels

In [15]:
df.head()

zone_id      pickup_hour_ts  demand  avg_fare  avg_distance  hour  \
0        1 2019-01-01 10:00:00       2     61.25         16.90    10   
1        1 2019-01-01 12:00:00       1    135.00         19.30    12   
2        1 2019-01-01 15:00:00       1    106.00         41.28    15   
3        1 2019-01-02 02:00:00       1     30.00          1.27     2   
4        1 2019-01-02 03:00:00       1     15.00         12.65     3   

   day_of_week  is_weekend  day  month  cluster  
0            1           0    1      1        3  
1            1           0    1      1        3  
2            1           0    1      1        3  
3            2           0    2      1        1  
4            2           0    2      1        1

In [16]:
df.to_parquet(
    "../../data/processed/zone_hour_clusters.parquet"
)